package com.mcp1993.greendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mcp1993.greendaodemo.bean.Challenge_horData;

import com.mcp1993.greendaodemo.dao.Challenge_horDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig challenge_horDataDaoConfig;

    private final Challenge_horDataDao challenge_horDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        challenge_horDataDaoConfig = daoConfigMap.get(Challenge_horDataDao.class).clone();
        challenge_horDataDaoConfig.initIdentityScope(type);

        challenge_horDataDao = new Challenge_horDataDao(challenge_horDataDaoConfig, this);

        registerDao(Challenge_horData.class, challenge_horDataDao);
    }
    
    public void clear() {
        challenge_horDataDaoConfig.clearIdentityScope();
    }

    public Challenge_horDataDao getChallenge_horDataDao() {
        return challenge_horDataDao;
    }

}
